### ISSUE TITLE
Not able to export only private key

### ISSUE THREAD

**Issue by deepakkoirala** [lucanaef/PGPro#77]
I just imported an private key only. When I tried to export the private key only. Its coming empty.

**Comment by lucanaef** [comment]
I'll close this issue since the fix has been merged in.

**Comment by deepakkoirala** [comment]
I can still see the issue in my app. Have it been released yet? Whats the plan?

**Comment by lucanaef** [comment]
It's currently in the beta version and will therefore be part of the next release.
